<?php

namespace App;

class Language extends \PHPixie\Plugin {
	
	private $lang = 'en';
	private $strings;
	private $isEnglish_ = false;
	private $english = array(
		'dpoint' => '.',
		'tseparator' => ',',
		'OK' => 'Ok',
		'Home' => 'Home',
		'Portfolio' => 'Portfolio',
		'Simulator' => 'Simulator',
		'YourPortfolio' => 'Your portfolio',
		'Login' => 'Login',
		'Logout' => 'Logout',
		'Profile' => 'Profile',
		'Register' => 'Crear FREE account',
		'CreateAccount' => 'Create account',
		'CreatePortfolio' => 'Create portfolio',
		'EmailExists' => 'That email is already registered',
		'OneStepToBegin' => 'One step to begin',
		'CreateAccountNow' => 'Create your portfolio FREE:',
		'EnterEmail' => 'Type in your email address to access Panda',
		'EmailPlaceholder' => 'Email address',
		'EnterPassword' => 'If your account has a password, enter it below:',
		'WantPassword' => 'If you want to use a password, enter it below',
		'PasswordPlaceholder' => 'Password (optional)',
		'RepeatPassword' => 'Repeat password (optional)',
		'SendEmail' => 'Enviar correo',
		'PasswordReset' => 'Reset password',
		'EmailInUse' => 'This e-mail address has already been registered',
		'ExpandWithPremium' => 'Expand your portfolio with Panda Premium',
		'PandaPremium' => 'Panda Premium',
		'Club30' => 'Panda Club 30\'',
		'WithPremium_1' => 'With Panda Premium you can follow up to 16 companies and 4 market indices.',
		'WithPremium_2' => 'Discounts with Panda-associated brokers.',
		'WithPremium_3' => 'Download the Panda guide to survival in the stock market.',
		'ExpandWithClub30' => 'Expand your portfolio with Panda Club30',
		'WithClub30_1' => 'All the benefits of Panda Premium.',
		'WithClub30_2' => 'Recieve Panda notifications 30 minutes before the markets open.',
		'Learn' => 'Learn',
		'Contact' => 'Contact',
		'LostPassword' => 'Lost your password?',
		'NoSuchEmail' => 'Invalid email address...',
		'EmailForReset' => 'Please enter your email and we\'ll send you a link to recover your password:',
		'ResetEmailSent' => 'An email has been sent with instructions on how to reset your password...',
		'PasswordWasReset1' => 'Your password has been successfully reset.',
		'PasswordWasReset2' => 'You can create a new password in the \'Profile\' menu.',
		'InvalidPasswordReset' => 'Invalid link!',
		'JustBought' => 'The Panda just bought stocks in',
		'JustSold' => 'The Panda just sold his stocks in',
		'NoOperations' => '(No active Panda operations)',
		'PandaPerformance' => 'Panda performance for your portfolio',
		'profit' => 'profit',
		'loss' => 'loss',
		'Companies' => 'Companies',
		'Performance' => 'Performance',
		'Profit3' => '3&nbsp;month',
		'Profit1' => '1&nbsp;year',
		'Profit2' => '2&nbsp;year',
		'Profit5' => '5&nbsp;year',
		'ChooseCompanies' => 'Select<br>companies',
		'disclaimer1' => "Estimated profits, calculated by placing the same 'seed' capital in each company/index (eg. $100) then simply following the Panda.",
		'disclaimer2' => "Profit estimations do not include stockbroker's fees or sales comissions. Past performance is no guarantee of future results.",
		'download1' => "With the Panda app installed on your smartphone/tablet you'll never miss an operation.",
		'download2' => "Receive automatic alerts for all Panda operations in your portfolio.",
		'download3' => "Relax and let The Panda do the work...",
		'downloadAndroid' => "Android users<br>Install now",
		'downloadApple' => "Apple iOS<br>coming soon",
		'WhatIsPanda' => "What is Broker Panda?",
		'PandaHome1' => 'Panda is a specialist in Big Data engineering specialized in publicly traded companies.',
		'PandaHome2' => 'Panda uses proprietary algorithms to analyze over 300 companies and market indices all over the world to create entry/exit models which can optimize any portfolio.',
		'PandaHome3' => 'The system of daily notifications keeps you informed and gives all your investments an advantage.',
		'PandaHome4' => 'Compare us with the others ... then get ready to follow The Panda.',
		'PandaHome5' => 'Follow The Panda or weep!',
		'MarketAnalysis' => 'Market Analysis',
		'AnalysisText' => 'Broker Panda provides a daily comparison and analysis of more than 300 companies and major market indices.',
		'HighProfitability' => 'High profitability',
		'HighProfitabilityText' => 'With our sophisticated algorithms, Broker Panda shows you the path to achieve long term profit with minimal risk.',
		'ThePandaApp' => 'The Panda App',
		'ThePandaAppText' => 'Install the free Panda App and The Panda will send strategically timed daily alerts directly to the palm of your hand.',
		'AsEasyAs' => "It's as easy as...",
		'ChoosePortfolio' => '1) Choose your portfolio',
		'ChoosePortfolioText1' => 'Broker Panda gives you access to a wide range of companies and indices from four different continents.',
		'ChoosePortfolioText2' => 'Freemium model: 4 companies.',
		'ChoosePortfolioText3' => 'Premium model: 16 companies.',
		'ChoosePortfolioText4' => "You're free to change companies whenever you want.",
		'FollowStrategy' => '2) Follow our strategy',
		'FollowStrategyText1' => "Follow the Panda's footprints in your portfolio to optimize your benefits and reduce risks in a sustainable way.",
		'FollowStrategyText2' => "Panda's buy/sell operations are shown as small colored icons in your list of companies.",
		'FollowStrategyText3' => "We work 24/7 to make sure the market never catches you unprepared.",
		'CompareWithMarket' => '3) Compare us with the market',
		'CompareWithMarketText1' => 'Transparency is our most important principle.',
		'CompareWithMarketText2' => "We'll show you how we minimize losses and how we use market tendencies to beat the competition and generate medium to long-term income.",
		'CompareWithMarketText3' => "Maybe you won't become a millionaire but you'll certainly beat your showoff friend, your annoying cousin and all the other know-it-alls of this world.",
		'CompareWithMarketText4' => 'Pablo Sabir&oacute;n, CEO, Broker Panda.',

		'Panda' => 'Panda',
		'Market' => 'Market',
		'USA' => 'USA',
		'Europe' => 'Europe',
		'LatinAmerica' => 'Latin America',
		'AsiaPacific' => 'Asia Pacific',
		'IndexComForex' => 'Index, Commodities, Forex',
		'Instructions' => 'Instructions',
		'Modified' => '(modified)',
		'RemoveCompanies' => 'Remove companies',
		'Cancel' => 'Cancel',
		'SaveThisPortfolio' => 'Save this portfolio',
		'SavingPortfolio' => 'Saving your portfolio...',
		'SaveError' => 'Error during save!',
		'PandaOperationsFor' => 'Panda ',
		'PandaHistoryFor' => 'Panda history for ',
		'HideChart' => 'Hide chart',
		'ClickForDetail' => 'Click a company to see details and Panda history...',
		'Secret' => 'Secret...',
		
		// Profile
		'Account' => 'My account:',
		'EmailAddress' => 'Email:',
		'AccountType' => 'Account type:',
		'AccountFree' => 'Panda Free',
		'AccountSmall' => 'Panda Small Investor',
		'AccountLarge' => 'Panda Large Investor',
		'AccountClub30' => 'Panda Club 30',
		'Cupon' => 'Cupon:',
		'ExpiryDate' => 'Expiry date:',
		'EmailAlerts' => 'Email alerts:',
		'Enabled' => 'Enabled',
		'EnableEU' => 'Europe',
		'EnableUSA' => 'USA',
		'EnableLatAm' => 'Latin&nbsp;America',
		'EnableAsia' => 'Asia',
		'Never' => 'Never',
		'Renew' => 'renew...',
		'Password' => 'Account password:',
		'AccountHasPassword' => 'This account has a password...',
		'AccountHasNoPassword' => 'This account has no password...',
		'RemovePassword' => 'Remove it!',
		'ChangePassword' => 'Change it!',
		'NewPassword' => 'Your new password',
		'RepeatNewPassword' => 'Repeat new password',
		'CreatePassword' => 'Create a password',
		'PasswordIsEmpty' => 'Error: Your new password cannot be empty',
		'PasswordsDontMatch' => "Error: The passwords don\'t match",
		'NewPasswordSet' => 'Your password has been updated successfully',
		'PasswordRemoved' => 'Password removed, your account now has no password...',
		'NoSuchAddress' => 'Unknown email address',
		'ClickToGoHome' => 'Click <a href="/">here</a> to return to the Panda Home page',
		'ThanksForConfirming' => 'Your account has been confirmed',
		'NowEnjoyTrial' => 'You can now enjoy Panda completely free for 30 days',
		'ClickToGoToPortfolio' => 'Click <a href="/dashboard/main">here</a> to continue to your portfolio...',
		'YouDidntConfirm' => 'You haven\'t confirmed your email address yet!',
		'PleaseCheckInbox1' => 'Please check the inbox for "',
		'PleaseCheckInbox2' => '" for email from brokerpanda.com',
		'ClickToResend' => 'Click <a href="/users/resendConfirmation">here</a> to resend the confirmation email...',
		'MyClients' => 'My clients',
		'NoClients' => 'You don\'t have any clients registered in BrokerPanda',

		// Subscription page
		'AccountExpired' => 'Your panda subscription has expired...',
		'FollowPandaIsCheap' => 'Choose your subscription option:',
		'SmallInvestors' => 'Small Investors',
		'LargeInvestors' => 'Large Investors',
		'Club30' => 'Panda Club 30',
		'PerWeek' => 'Per week',
		'FourCompanies' => '4 portfolio alerts',
		'SixteenCompanies' => '16 portfolio alerts',
		'Alert30' => 'Alerts 30 minutes before the markets open',

		// Summary
		'Summary' => 'Summary',
		'PandaSummary' => 'Summary of Panda operations ',
		'Close' => 'Close',
		'Continent' => 'Continent',
		'Exchange' => 'Exchange',
		'Company' => 'Company',
		'BuySell' => 'Buy/Sell',
		'Buy' => 'Buy',
		'Sell' => 'Sell',
		'Price' => 'Price',
		'AlertStart' => 'Start',
		'AlertEnd' => 'End',

		// Help
		'follow_steps1' => 'To learn to use Broker Panda, follow the footsteps. It\'s as easy as 1, 2, 3...', 
		'follow_find' => 'Look for the numbered footsteps in the page',
		'help1title' => 'The Markets',
		'help1text1' => 'In this section we see the principal stock markets of the world.',
		'help1text2' => 'If you see a panda in any market there has been activity in that market. '.
										'Look among the market\'s companies to find individual activity signals.',
		'help2title' => 'The companies',
		'help2text1' => 'Select any market index to see individual companies, IBEX for example.',
		'help2text2' => 'Changes of trend are marked with colored pandas: Red pandas for upward trends, green pandas for downward trends.',
		'help2up' => 'Up change',
		'help2down' => 'Down change',
		'help3title' => 'The portfolio',
		'help3text1' => 'You can place interesting companies in your personal portfolio. '.
										'You\'ll receive notifications about these companies via. email and through the Panda App. '.
										'For maximum performance it\'s important to add any companies you may have acquired to your portfolio, '.
										'the notifications will help you to take prompt action when the company changes trend.',
		'help3text2' => 'Use the checkboxes at the side of each company to add them to your portfolio. '.
										'To remove a company, unmark the checkbox or use the "Remove companies" button on the right. ',
		'help4title' => 'Statistics',
		'help4text1' => 'Select any company to see performance statistics and detailed Panda history.',
		'help5title' => 'Performance',
		'help5text1' => 'This graph shows the recent performance of the companies in your portfolio (percent growth).',

		// Simulator
		'SimAccount' => 'User account:',
		'UserName' => 'User name:',
		'UserRank' => 'Ranking:',
		'RemainingTime' => 'Remaining:',
		'Balance' => 'Account balance:',
		'Profit' => 'Your profit:',
		'Invested' => 'Invested:',
		'Liquidity' => 'Liquidity:',
		'BuyShares' => 'Buy more shares...', 
		
		'SimOwned' => 'Shares owned:',
		'SimCompany' => 'Company',
		'SimNumShares' => 'Shares',
		'SimBuyPrice' => 'Buy Price',
		'SimInvestment' => 'Investment',
		'SimSellPrice' => 'Sell price',
		'SimCurrentPrice' => 'Current price',
		'SimMarketValue' => 'Current value',
		'SimProfit' => 'Profit',
		'SimSell' => 'Sell...',
		
		'SimHistory' => 'History:'
	);
	private $spanish = array(
		'dpoint' => ',',
		'tseparator' => '.',
		'Home' => 'Inicio',
		'Portfolio' => 'Portafolio',
		'Simulator' => 'Simulador de bolsa',
		'YourPortfolio' => 'Tu portafolio',
		'Login' => 'Entrar',
		'Logout' => 'Salir',
		'Profile' => 'Perfil',
		'Learn' => 'Aprender',
		'Contact' => 'Contactar',
		'Register' => 'Crear cuenta GRATIS',
		'CreateAccount' => 'Crear cuenta',
		'CreatePortfolio' => 'Crear portafolio',
		'EmailExists' => 'Error: El correo introducido est&aacute; registrado previamente',
		'OneStepToBegin' => 'Un paso para empezar',
		'CreateAccountNow' => 'Reg&iacute;strate y consigue tu portafolio GRATIS:',
		'EnterEmail' => 'Introduce tu correo electronico:',
		'EmailPlaceholder' => 'Direcci&oacute;n correo electronico',
		'EnterPassword' => 'Si tu cuenta tiene contrase&ntilde;a, introducelo abajo:',
		'WantPassword' => 'Si quieres usar una contrase&ntilde;a, introducelo abajo:',
		'PasswordPlaceholder' => 'Contrase&ntilde;a (opcional)',
		'RepeatPassword' => 'Repitir Contrase&ntilde;a (opcional)',
		'EmailInUse' => 'La direcci&oacute;n de correo est&aacute; previamente registrada',
		'ExpandWithPremium' => 'Ampliar tu portafolio con una cuenta Panda Premium',
		'WithPremium_1' => 'Portafolio con hasta 16 compa&ntilde;&iacute;as y 4 indices.',
		'WithPremium_2' => 'Descuentos con nuestros brokers partner.',
		'WithPremium_3' => 'Descarga gratuita de nuestra guia practica para sobrevivir en bolsa.',
		'ExpandWithClub30' => 'Panda Club30 - para los mas expertos',
		'WithClub30_1' => 'Todos los beneficios de Panda Premium.',
		'WithClub30_2' => 'Los avisos Panda llegan 30 minutos antes de la apertura de los mercados.',
		'EmailForReset' => 'Introduce tu correo electronico para recibir un vinculo para borrar tu contrase&ntilde;a:',
		'ResetEmailSent' => 'Ha sido enviado un correo con instrucciones para borrar tu contrase&ntilde;a...',
		'LostPassword' => '&iquest;Has olvidado tu contrase&ntilde;a?',
		'NoSuchEmail' => 'La direcci&oacute;n de correo no es valido...',
		'PasswordWasReset1' => 'Tu contrase&ntilde;a ha sido borrado con exito.',
		'PasswordWasReset2' => 'Para crear una contrase&ntilde;a nueva, ir al menu \'Perfil\'.',
		'InvalidPasswordReset' => 'El vinculo no es valido.',
		'JustBought' => 'El Panda acaba de comprar acci&oacute;nes en',
		'JustSold' => 'El Panda acaba de vender sus acci&oacute;nes en',
		'NoOperations' => '(No hay operaciones Panda activas)',
		'PandaPerformance' => 'Rendimiento Panda para este portfolio',
		'profit' => 'ganancias',
		'loss' => 'perdidas',
		'Companies' => 'Compa&ntilde;ias',
		'Performance' => 'Rendimiento',
		'Profit3' => '3&nbsp;meses',
		'Profit1' => '1&nbsp;a&ntilde;o',
		'Profit2' => '2&nbsp;a&ntilde;os',
		'Profit5' => '5&nbsp;a&ntilde;os',
		'ChooseCompanies' => 'Elegir<br>compa&ntilde;&iacute;as',
		'disclaimer1' => "Ganancias estimadas, calculadas depositando el mismo capital 'semilla' en cada compa&ntilde;&iacute;a/indice (eg. $100) y simplemente siguiendo El Panda.",
		'disclaimer2' => "Las estimaci&oacute;nes no incluyen gastos ni comisi&oacute;nes de compraventa. El rendimiento pasado no es garant&iacute;a de resultados futuros.",
		'download1' => "Con la app de Broker Panda instalado en tu m&oacute;vil / tablet no perder&aacute;s ni una sola operaci&oacute;n.",
		'download2' => "Recibir&aacute;s alertas automaticas para las operaci&oacute;nes Panda en tu portfolio.",
		'download3' => "Relajate y deja que Broker Panda se ocupa de todo...",
		'downloadAndroid' => "Android<br>Instalar ahora",
		'downloadApple' => "Apple iOS<br>disponible pronto",
		'WhatIsPanda' => '&iquest;Qu&eacute; es Broker Panda?',
		'PandaHome1' => 'Broker Panda es una ingenieria especializada en Big Data de tratamiento de compa&ntilde;ias cotizadas.',
		'PandaHome2' => 'Broker Panda analiza con sus propios algoritmos m&aacute;s de 300 compa&ntilde;ias de todo el mundo y sus &iacute;ndices, proporcionando modelos de entrada y salida propios para ayudar a optimizar cualquier portfolio.',
		'PandaHome3' => 'Su sistema de notificaci&oacute;n diario le permite estar siempre informado y poder aprovechar esa ventaja.',
		'PandaHome4' => 'Comp&aacute;renos por favor, y luego s&iacute;ganos o llore.',
		'PandaHome5' => 'Follow the Panda or weep!',
		'MarketAnalysis' => 'An&aacute;lisis diario',
		'AnalysisText' => 'Broker Panda analiza, compara y toma decisiones diarias en m&aacute;s de 300 compa&ntilde;ias y en los indices principales.',
		'HighProfitability' => 'Alta rentabilidad',
		'HighProfitabilityText' => 'Con nuestros sofisticados algoritmos, Broker Panda desvela el camino hacia ganancias a largo plazo y siempre con m&iacute;nimo riesgo.',
		'ThePandaApp' => 'La App de Panda',
		'ThePandaAppText' => 'Instala gratis la App de Broker Panda y enviaremos las notificaciones a primera hora directamente a la palma de tu mano.',
		'AsEasyAs' => 'Es tan f&aacute;cil como...',
		'ChoosePortfolio' => '1) Selecciona tu portfolio',
		'ChoosePortfolioText1' => 'Broker Panda da acceso a una gama amplia de compa&ntilde;ias y indices de cuatro continentes diferentes.',
		'ChoosePortfolioText2' => 'Modelo Freemium: 4 compa&ntilde;ias.',
		'ChoosePortfolioText3' => 'Modelo Premium: 16 compa&ntilde;ias.',
		'ChoosePortfolioText4' => 'Podras cambiarlas cuando quieras.',
		'FollowStrategy' => '2) Sigue nuestra estrategia',
		'FollowStrategyText1' => "Sigue las huellas de Panda en tu portfolio para optimizar tus ganancias y reducir riesgos de manera sostenible.",
		'FollowStrategyText2' => "Recibiras los avisos en forma de peque&ntilde;os iconos de colores de nuestras compras y ventas del la jornada anterior.",
		'FollowStrategyText3' => "Trabajamos 24/7 para que los cambios del mercado no te sorprendan.",
		'CompareWithMarket' => '3) Comp&aacute;ranos con el mercado',
		'CompareWithMarketText1' => 'La transparencia es nuestro principio m&aacute;s importante.',
		'CompareWithMarketText2' => 'Te mostramos c&oacute;mo minimizamos las p&eacute;rdidas y c&oacute;mo utilizamos las tendencias del mercado para batir a la competencia y generar ingresos a medio y largo plazo.',
		'CompareWithMarketText3' => 'Puede que no te hagas millonario pero seguro que ganas a tu amigo fanfarr&oacute;n, al pesado de tu cu&ntilde;ado y al listo ese que lo sabe todo.',
		'CompareWithMarketText4' => 'Pablo Sabir&oacute;n, CEO, Broker Panda.',

		'Panda' => 'Panda',
		'Market' => 'Mercado',
		'USA' => 'USA',
		'Europe' => 'Europa',
		'LatinAmerica' => 'America Latina',
		'AsiaPacific' => 'Asia Pacific',
		'Instructions' => 'Instrucciones',
		'Modified' => '(modificado)',
		'RemoveCompanies' => 'Quitar compa&ntilde;ias',
		'Cancel' => 'Cancelar',
		'SaveThisPortfolio' => 'Guardar este portafolio',
		'SavingPortfolio' => 'Guardando tu portafolio...',
		'SaveError' => 'Error durante la operacion!',
		'PandaOperationsFor' => 'Panda: ',
		'PandaHistoryFor' => 'Historal Panda para ',
		'HideChart' => 'Ocultar',
		'ClickForDetail' => 'Selecciona una compa&ntilde;&iacute;a para ver detalles y historial Panda...',
		'Secret' => 'Secreto...',

		// Profile
		'Account' => 'Mi cuenta:',
		'EmailAddress' => 'Correo:',
		'AccountType' => 'Tipo de cuenta:',
		'AccountFree' => 'Panda Free',
		'AccountSmall' => 'Panda Peque&ntilde;o Inversor',
		'AccountLarge' => 'Panda Gran Inversor',
		'AccountClub30' => 'Panda Club 30',
		'Cupon' => 'Cupon:',
		'ExpiryDate' => 'Caducidad:',
		'EmailAlerts' => 'Alertas por email:',
		'Enabled' => 'Habilitado',
		'EnableEU' => 'Europa',
		'EnableUSA' => 'USA',
		'EnableLatAm' => 'America&nbsp;Latina',
		'EnableAsia' => 'Asia',
		'Never' => 'Nunca',
		'Renew' => 'renovar...',
		'Password' => 'Mi contrase&ntilde;a:',
		'AccountHasPassword' => 'Tu cuenta tiene contrase&ntilde;a...',
		'AccountHasNoPassword' => 'Tu cuenta no tiene contrase&ntilde;a...',
		'RemovePassword' => 'Quitar contrase&ntilde;a',
		'ChangePassword' => 'Cambiar contrase&ntilde;a',
		'NewPassword' => 'Contrase&ntilde;a nueva',
		'RepeatNewPassword' => 'Repitir contrase&ntilde;a nueva',
		'CreatePassword' => 'Crear una contrase&ntilde;a',
		'NewPasswordSet' => 'Contrase&ntilde;a establecida con ex&iacute;to...',
		'PasswordRemoved' => 'Contrase&ntilde;a borrada, tu cuenta ya no tiene contrase&ntilde;a...',
		'NoSuchAddress' => 'Direcci&oacute;n de correo electr&oacute;nico desconocido...',
		'ClickToGoHome' => 'Pincha <a href="/">aqu&iacute;</a> para volver a la pagina principal',
		'ThanksForConfirming' => 'Su cuenta ha sido confirmado con ex&iacute;to',
		'NowEnjoyTrial' => 'Ahora puedes disfrutar de Panda libremente durante 30 dias',
		'ClickToGoToPortfolio' => 'Pincha <a href="/dashboard/main">aqu&iacute;</a> para continuar a tu portafolio...',
		'YouDidntConfirm' => 'Todavia no has confirmado tu direcci&oacute;n de correo electronico!',
		'PleaseCheckInbox1' => 'Por favor comprueba la bandeja de entrada de "',
		'PleaseCheckInbox2' => '" para ver si hay correo de brokerpanda.com',
		'ClickToResend' => 'Pincha <a href="/users/resendConfirmation">aqu&iacute;</a> para volver a enviar el correo de confirmaci&oacute;n...',
		'MyClients' => 'Mis clientes',
		'NoClients' => 'Actualmente no tienes ningun cliente registrado en BrokerPanda',

		// Subscription page
		'AccountExpired' => 'Tu cuenta Panda ha caducado...',
		'FollowPandaIsCheap' => 'Elige tu opci&oacute;n de abonado:',
		'SmallInvestors' => 'Peque&ntilde;os inversores',
		'LargeInvestors' => 'Grandes inversores',
		'Club30' => 'Panda Club 30',
		'PerWeek' => 'Por semana',
		'FourCompanies' => '4 alertas en portafolio',
		'SixteenCompanies' => '16 alertas en portafolio',
		'Alert30' => 'Alertas 30 minutos antes de la apertura de los mercados',

		// Help
		'follow_steps1' => 'Para aprender a user Broker Panda, siga las huellas numeradas. Es tan facil como 1, 2, 3...', 
		'follow_find' => 'Busca las huellas numeradas dentro de la pagina',
		'help1title' => 'Los Mercados',
		'help1text1' => 'En esta seccion vemos los principales mercados del mundo.',
		'help1text2' => 'Si aparece un pandita en cualquier mercado, se han producido cambios de tendencia alli. '.
										'Busca entre las compa&ntilde;&iacute;as de ese mercado para encontrar las se&ntilde;ales m&aacute;s interesantes.',
		'help2title' => 'Las Compa&ntilde;&iacute;as',
		'help2text1' => 'Seleccione cualquier mercado para ver sus compa&ntilde;&iacute;as, por ejemplo el IBEX.',
		'help2text2' => 'Las se&ntilde;ales de cambio de tendencia están marcadas con pandas: Pandas verdes para cambios alcistas, pandas rojos para bajistas.',
		'help2up' => 'Alcista',
		'help2down' => 'Bajista',
		'help3title' => 'El portafolio',
		'help3text1' => 'En el portafolio colocamos compa&ntilde;&iacute;as de especial inter&eacute;s. '.
										'Recibir&aacute; notificaciones	sobre ellos por correo electr&oacute;nico y atraves de nuestro app. '.
										'Para	maximizar sus beneficios es muy important agregar cualquier compa&ntilde;&iacute;a que hayas '.
										'adquirido a su portafolio. De ese modo puede asegurar la venta putual cuando cambian las '.
										'tendencias del mercado.',
		'help3text2' => 'Para agregar compa&ntilde;&iacute;as a su portafolio, marque las casillas correspondientes. '.
										'Para quitar una compa&ntilde;&iacute;a, desmarque la casilla o usar el boton "quitar compa&ntilde;&iacute;as". ',
		'help4title' => 'Estadísticas',
		'help4text1' => 'Seleccione cualquier compa&ntilde;&iacute;a para ver su historial Panda y estadística detallada.',
		'help5title' => 'Rendimiento',
		'help5text1' => 'El rendimiento de su portafolio personal en los ultimos meses se muestra en el gr&aacute;fico abajo (porcentaje).',

		// Summary
		'Summary' => 'Resumen',
		'PandaSummary' => 'Resumen operaciones Panda ',
		'Close' => 'Cerrar',
		'Continent' => 'Continente',
		'Exchange' => 'Indice',
		'Company' => 'Compa&ntilde;&iacute;a',
		'BuySell' => 'Comprar/Vender',
		'Buy' => 'Comprar',
		'Sell' => 'Vender',
		'Price' => 'Precio',

		// Simulator
		'SimAccount' => 'Simulador de bolsa:',
		'UserName' => 'Nombre usuario:',
		'UserRank' => 'Ranking:',
		'RemainingTime' => 'Tiempo restante:',
		'Balance' => 'Valor cuenta:',
		'Profit' => 'Ganancias:',
		'Invested' => 'Dinero en bolsa:',
		'Liquidity' => 'Liquidez:',
		'BuyShares' => 'Comprar acci&oacute;nes...', 

		'SimOwned' => 'Tus acci&oacute;nes',
		'SimCompany' => 'Compa&ntilde;&iacute;a',
		'SimNumShares' => 'Acciones',
		'SimBuyPrice' => 'Precio compra',
		'SimInvestment' => 'Inversi&oacute;n',
		'SimSellPrice' => 'Precio venta',
		'SimCurrentPrice' => 'Precio actual',
		'SimMarketValue' => 'Valor actual',
		'SimProfit' => 'Beneficio',
		'SimSell' => 'Vender...',
		
		'SimHistory' => 'Historial'
	);
	public function setLanguage($t) {
		if ($t === 'es') {
			$this->lang = $t;
			$this->isEnglish_ = false;
			$this->strings = $this->spanish;
		}
		else {
			$this->lang = $t;
			$this->isEnglish_ = true;
			$this->strings = $this->english;
		}
	}
	public function language() {
		return $this->lang;
	}
	public function __get($s) {
		if (array_key_exists($s, $this->strings)) {
      return $this->strings[$s];
    }
		else if (array_key_exists($s, $this->english)) {
      return $this->english[$s];
    }
		return '????';
	}
	public function isEnglish() {
		return $this->isEnglish_;
	}
};
